// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx AuditActionGroup object.</summary>
public readonly struct AuditActionGroupWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public AuditActionGroupWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the ActionGroup property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.AuditActionGroupType ActionGroup => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.AuditActionGroupType>(Microsoft.SqlServer.Dac.Model.AuditActionGroup.ActionGroup);
}

public static class AuditActionGroupExtensions
{
    public static AuditActionGroupWrapper ToAuditActionGroup(this TSqlObject wrapper) => new AuditActionGroupWrapper(wrapper);
}