// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx BrokerPriority object.</summary>
public readonly struct BrokerPriorityWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public BrokerPriorityWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the RemoteServiceName property.</summary>
    public string? RemoteServiceName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.BrokerPriority.RemoteServiceName);
    /// <summary>Gets the PriorityLevel property.</summary>
    public int PriorityLevel => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.BrokerPriority.PriorityLevel);
    ///<summary>
    /// Name: ContractName. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ContractName => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.BrokerPriority.ContractName);
    ///<summary>
    /// Name: LocalServiceName. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> LocalServiceName => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.BrokerPriority.LocalServiceName);
}

public static class BrokerPriorityExtensions
{
    public static BrokerPriorityWrapper ToBrokerPriority(this TSqlObject wrapper) => new BrokerPriorityWrapper(wrapper);
}