// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx BrokerPriority object.</summary>
public readonly struct BrokerPriorityWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public BrokerPriorityWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the RemoteServiceName property.</summary>
    public string? RemoteServiceName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.BrokerPriority.RemoteServiceName);
    /// <summary>Gets the PriorityLevel property.</summary>
    public int PriorityLevel => ObjectType.GetProperty<int>(Microsoft.SqlServer.Dac.Model.BrokerPriority.PriorityLevel);
    ///<summary>
    /// Name: ContractName. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ContractName => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.BrokerPriority.ContractName);
    ///<summary>
    /// Name: LocalServiceName. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> LocalServiceName => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.BrokerPriority.LocalServiceName);
}

public static class BrokerPriorityExtensions
{
    public static BrokerPriorityWrapper ToBrokerPriority(this TSqlObject wrapper) => new BrokerPriorityWrapper(wrapper);
}