// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx BuiltInServerRole object.</summary>
public readonly struct BuiltInServerRoleWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public BuiltInServerRoleWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
}

public static class BuiltInServerRoleExtensions
{
    public static BuiltInServerRoleWrapper ToBuiltInServerRole(this TSqlObject wrapper) => new BuiltInServerRoleWrapper(wrapper);
}