// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ClrTypeProperty object.</summary>
public readonly struct ClrTypePropertyWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ClrTypePropertyWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Name property.</summary>
    public string? Name => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ClrTypeProperty.Name);
    ///<summary>
    /// Name: ClrType. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ClrType => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.ClrTypeProperty.ClrType);
}

public static class ClrTypePropertyExtensions
{
    public static ClrTypePropertyWrapper ToClrTypeProperty(this TSqlObject wrapper) => new ClrTypePropertyWrapper(wrapper);
}