// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ColumnMasterKey object.</summary>
public readonly struct ColumnMasterKeyWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ColumnMasterKeyWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the AllowEnclaveComputations property.</summary>
    public bool AllowEnclaveComputations => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ColumnMasterKey.AllowEnclaveComputations);
    /// <summary>Gets the KeyPath property.</summary>
    public string? KeyPath => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ColumnMasterKey.KeyPath);
    /// <summary>Gets the KeyStoreProviderName property.</summary>
    public string? KeyStoreProviderName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ColumnMasterKey.KeyStoreProviderName);
    /// <summary>Gets the Signature property.</summary>
    public string? Signature => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ColumnMasterKey.Signature);
}

public static class ColumnMasterKeyExtensions
{
    public static ColumnMasterKeyWrapper ToColumnMasterKey(this TSqlObject wrapper) => new ColumnMasterKeyWrapper(wrapper);
}