// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ColumnEncryptionKeyValue object.</summary>
public readonly struct ColumnEncryptionKeyValueWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ColumnEncryptionKeyValueWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the EncryptedValue property.</summary>
    public string? EncryptedValue => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ColumnEncryptionKeyValue.EncryptedValue);
    /// <summary>Gets the EncryptionAlgorithm property.</summary>
    public string? EncryptionAlgorithm => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ColumnEncryptionKeyValue.EncryptionAlgorithm);
    ///<summary>
    /// Name: ColumnMasterKey. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ColumnMasterKey => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.ColumnEncryptionKeyValue.ColumnMasterKey);
}

public static class ColumnEncryptionKeyValueExtensions
{
    public static ColumnEncryptionKeyValueWrapper ToColumnEncryptionKeyValue(this TSqlObject wrapper) => new ColumnEncryptionKeyValueWrapper(wrapper);
}