// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Credential object.</summary>
public readonly struct CredentialWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public CredentialWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Identity property.</summary>
    public string? Identity => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Credential.Identity);
    /// <summary>Gets the Secret property.</summary>
    public string? Secret => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Credential.Secret);
    ///<summary>
    /// Name: CryptographicProvider. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> CryptographicProvider => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Credential.CryptographicProvider);
}

public static class CredentialExtensions
{
    public static CredentialWrapper ToCredential(this TSqlObject wrapper) => new CredentialWrapper(wrapper);
}