// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx CryptographicProvider object.</summary>
public readonly struct CryptographicProviderWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public CryptographicProviderWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the DllPath property.</summary>
    public string? DllPath => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.CryptographicProvider.DllPath);
    /// <summary>Gets the Enabled property.</summary>
    public bool Enabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.CryptographicProvider.Enabled);
}

public static class CryptographicProviderExtensions
{
    public static CryptographicProviderWrapper ToCryptographicProvider(this TSqlObject wrapper) => new CryptographicProviderWrapper(wrapper);
}