// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DatabaseEncryptionKey object.</summary>
public readonly struct DatabaseEncryptionKeyWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DatabaseEncryptionKeyWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Algorithm property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SymmetricKeyAlgorithm Algorithm => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.SymmetricKeyAlgorithm>(Microsoft.SqlServer.Dac.Model.DatabaseEncryptionKey.Algorithm);
    ///<summary>
    /// Name: Certificate. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Certificate => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseEncryptionKey.Certificate);
    ///<summary>
    /// Name: AsymmetricKey. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> AsymmetricKey => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseEncryptionKey.AsymmetricKey);
}

public static class DatabaseEncryptionKeyExtensions
{
    public static DatabaseEncryptionKeyWrapper ToDatabaseEncryptionKey(this TSqlObject wrapper) => new DatabaseEncryptionKeyWrapper(wrapper);
}