// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DatabaseAuditSpecification object.</summary>
public readonly struct DatabaseAuditSpecificationWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DatabaseAuditSpecificationWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the WithState property.</summary>
    public bool WithState => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseAuditSpecification.WithState);
    ///<summary>
    /// Name: AuditActionGroups. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> AuditActionGroups => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseAuditSpecification.AuditActionGroups);
    ///<summary>
    /// Name: AuditActions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> AuditActions => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseAuditSpecification.AuditActions);
    ///<summary>
    /// Name: ServerAudit. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ServerAudit => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseAuditSpecification.ServerAudit);
}

public static class DatabaseAuditSpecificationExtensions
{
    public static DatabaseAuditSpecificationWrapper ToDatabaseAuditSpecification(this TSqlObject wrapper) => new DatabaseAuditSpecificationWrapper(wrapper);
}