// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DatabaseEventNotification object.</summary>
public readonly struct DatabaseEventNotificationWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DatabaseEventNotificationWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the WithFanIn property.</summary>
    public bool WithFanIn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseEventNotification.WithFanIn);
    /// <summary>Gets the BrokerService property.</summary>
    public string? BrokerService => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseEventNotification.BrokerService);
    /// <summary>Gets the BrokerInstanceSpecifier property.</summary>
    public string? BrokerInstanceSpecifier => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseEventNotification.BrokerInstanceSpecifier);
    ///<summary>
    /// Name: EventGroup. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventGroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseEventNotification.EventGroup);
    ///<summary>
    /// Name: EventType. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventType => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseEventNotification.EventType);
}

public static class DatabaseEventNotificationExtensions
{
    public static DatabaseEventNotificationWrapper ToDatabaseEventNotification(this TSqlObject wrapper) => new DatabaseEventNotificationWrapper(wrapper);
}