// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DatabaseCredential object.</summary>
public readonly struct DatabaseCredentialWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DatabaseCredentialWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Identity property.</summary>
    public string? Identity => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseCredential.Identity);
    /// <summary>Gets the Secret property.</summary>
    public string? Secret => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseCredential.Secret);
}

public static class DatabaseCredentialExtensions
{
    public static DatabaseCredentialWrapper ToDatabaseCredential(this TSqlObject wrapper) => new DatabaseCredentialWrapper(wrapper);
}