// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DatabaseOptions object.</summary>
public readonly struct DatabaseOptionsWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DatabaseOptionsWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the CompatibilityLevel property.</summary>
    public int CompatibilityLevel => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.CompatibilityLevel);
    /// <summary>Gets the AcceleratedDatabaseRecovery property.</summary>
    public bool? AcceleratedDatabaseRecovery => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AcceleratedDatabaseRecovery);
    /// <summary>Gets the AllowSnapshotIsolation property.</summary>
    public bool AllowSnapshotIsolation => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AllowSnapshotIsolation);
    /// <summary>Gets the AnsiNullDefaultOn property.</summary>
    public bool AnsiNullDefaultOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AnsiNullDefaultOn);
    /// <summary>Gets the AnsiNullsOn property.</summary>
    public bool AnsiNullsOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AnsiNullsOn);
    /// <summary>Gets the AnsiPaddingOn property.</summary>
    public bool AnsiPaddingOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AnsiPaddingOn);
    /// <summary>Gets the AnsiWarningsOn property.</summary>
    public bool AnsiWarningsOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AnsiWarningsOn);
    /// <summary>Gets the ArithAbortOn property.</summary>
    public bool ArithAbortOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ArithAbortOn);
    /// <summary>Gets the AutoClose property.</summary>
    public bool AutoClose => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoClose);
    /// <summary>Gets the AutoCreateStatistics property.</summary>
    public bool AutoCreateStatistics => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoCreateStatistics);
    /// <summary>Gets the AutoCreateStatisticsIncremental property.</summary>
    public bool AutoCreateStatisticsIncremental => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoCreateStatisticsIncremental);
    /// <summary>Gets the AutoShrink property.</summary>
    public bool AutoShrink => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoShrink);
    /// <summary>Gets the AutoUpdateStatisticsAsync property.</summary>
    public bool AutoUpdateStatisticsAsync => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoUpdateStatisticsAsync);
    /// <summary>Gets the AutoUpdateStatistics property.</summary>
    public bool AutoUpdateStatistics => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutoUpdateStatistics);
    /// <summary>Gets the OptimizedLocking property.</summary>
    public bool? OptimizedLocking => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.OptimizedLocking);
    /// <summary>Gets the AutomaticIndexCompaction property.</summary>
    public bool? AutomaticIndexCompaction => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.AutomaticIndexCompaction);
    /// <summary>Gets the HonorBrokerPriority property.</summary>
    public bool HonorBrokerPriority => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.HonorBrokerPriority);
    /// <summary>Gets the ChangeTrackingAutoCleanup property.</summary>
    public bool ChangeTrackingAutoCleanup => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ChangeTrackingAutoCleanup);
    /// <summary>Gets the ChangeTrackingEnabled property.</summary>
    public bool ChangeTrackingEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ChangeTrackingEnabled);
    /// <summary>Gets the ConcatNullYieldsNull property.</summary>
    public bool ConcatNullYieldsNull => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ConcatNullYieldsNull);
    /// <summary>Gets the CursorCloseOnCommit property.</summary>
    public bool CursorCloseOnCommit => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.CursorCloseOnCommit);
    /// <summary>Gets the CursorDefaultGlobalScope property.</summary>
    public bool CursorDefaultGlobalScope => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.CursorDefaultGlobalScope);
    /// <summary>Gets the DateCorrelationOptimizationOn property.</summary>
    public bool DateCorrelationOptimizationOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DateCorrelationOptimizationOn);
    /// <summary>Gets the DBChainingOn property.</summary>
    public bool DBChainingOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DBChainingOn);
    /// <summary>Gets the WithEncryption property.</summary>
    public bool WithEncryption => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.WithEncryption);
    /// <summary>Gets the FullTextEnabled property.</summary>
    public bool FullTextEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.FullTextEnabled);
    /// <summary>Gets the NestedTriggersOn property.</summary>
    public bool NestedTriggersOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.NestedTriggersOn);
    /// <summary>Gets the NumericRoundAbortOn property.</summary>
    public bool NumericRoundAbortOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.NumericRoundAbortOn);
    /// <summary>Gets the DatabaseStateOffline property.</summary>
    public bool DatabaseStateOffline => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DatabaseStateOffline);
    /// <summary>Gets the QuotedIdentifierOn property.</summary>
    public bool QuotedIdentifierOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QuotedIdentifierOn);
    /// <summary>Gets the TransactionIsolationReadCommittedSnapshot property.</summary>
    public bool TransactionIsolationReadCommittedSnapshot => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TransactionIsolationReadCommittedSnapshot);
    /// <summary>Gets the ReadOnly property.</summary>
    public bool ReadOnly => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ReadOnly);
    /// <summary>Gets the RecursiveTriggersOn property.</summary>
    public bool RecursiveTriggersOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.RecursiveTriggersOn);
    /// <summary>Gets the SupplementalLoggingOn property.</summary>
    public bool SupplementalLoggingOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.SupplementalLoggingOn);
    /// <summary>Gets the TornPageProtectionOn property.</summary>
    public bool TornPageProtectionOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TornPageProtectionOn);
    /// <summary>Gets the TransformNoiseWords property.</summary>
    public bool TransformNoiseWords => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TransformNoiseWords);
    /// <summary>Gets the Trustworthy property.</summary>
    public bool Trustworthy => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.Trustworthy);
    /// <summary>Gets the VardecimalStorageFormatOn property.</summary>
    public bool VardecimalStorageFormatOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.VardecimalStorageFormatOn);
    /// <summary>Gets the UserAccessOption property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.UserAccessOption UserAccessOption => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.UserAccessOption>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.UserAccessOption);
    /// <summary>Gets the DelayedDurabilityMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.DelayedDurabilityMode DelayedDurabilityMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.DelayedDurabilityMode>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DelayedDurabilityMode);
    /// <summary>Gets the MemoryOptimizedElevateToSnapshot property.</summary>
    public bool MemoryOptimizedElevateToSnapshot => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.MemoryOptimizedElevateToSnapshot);
    /// <summary>Gets the DataRetentionEnabled property.</summary>
    public bool? DataRetentionEnabled => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DataRetentionEnabled);
    /// <summary>Gets the CatalogCollation property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.CatalogCollation? CatalogCollation => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.CatalogCollation?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.CatalogCollation);
    /// <summary>Gets the ChangeTrackingRetentionPeriod property.</summary>
    public int ChangeTrackingRetentionPeriod => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ChangeTrackingRetentionPeriod);
    /// <summary>Gets the ChangeTrackingRetentionUnit property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.TimeUnit ChangeTrackingRetentionUnit => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.TimeUnit>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ChangeTrackingRetentionUnit);
    /// <summary>Gets the Collation property.</summary>
    public string? Collation => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.Collation);
    /// <summary>Gets the Containment property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.Containment Containment => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.Containment>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.Containment);
    /// <summary>Gets the DefaultFullTextLanguage property.</summary>
    public string? DefaultFullTextLanguage => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DefaultFullTextLanguage);
    /// <summary>Gets the DefaultLanguage property.</summary>
    public string? DefaultLanguage => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DefaultLanguage);
    /// <summary>Gets the DWCompatibilityLevel property.</summary>
    public int DWCompatibilityLevel => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DWCompatibilityLevel);
    /// <summary>Gets the FileStreamDirectoryName property.</summary>
    public string? FileStreamDirectoryName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.FileStreamDirectoryName);
    /// <summary>Gets the IsLedgerOn property.</summary>
    public bool IsLedgerOn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.IsLedgerOn);
    /// <summary>Gets the LegacyCardinalityEstimation property.</summary>
    public bool LegacyCardinalityEstimation => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.LegacyCardinalityEstimation);
    /// <summary>Gets the LegacyCardinalityEstimationForSecondary property.</summary>
    public bool? LegacyCardinalityEstimationForSecondary => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.LegacyCardinalityEstimationForSecondary);
    /// <summary>Gets the MaxDop property.</summary>
    public int MaxDop => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.MaxDop);
    /// <summary>Gets the MaxDopForSecondary property.</summary>
    public int? MaxDopForSecondary => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.MaxDopForSecondary);
    /// <summary>Gets the NonTransactedFileStreamAccess property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.NonTransactedFileStreamAccess NonTransactedFileStreamAccess => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.NonTransactedFileStreamAccess>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.NonTransactedFileStreamAccess);
    /// <summary>Gets the PageVerifyMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.PageVerifyMode PageVerifyMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.PageVerifyMode>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.PageVerifyMode);
    /// <summary>Gets the ParameterizationOption property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.ParameterizationOption ParameterizationOption => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.ParameterizationOption>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ParameterizationOption);
    /// <summary>Gets the ParameterSniffing property.</summary>
    public bool ParameterSniffing => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ParameterSniffing);
    /// <summary>Gets the ParameterSniffingForSecondary property.</summary>
    public bool? ParameterSniffingForSecondary => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ParameterSniffingForSecondary);
    /// <summary>Gets the QueryOptimizerHotfixes property.</summary>
    public bool QueryOptimizerHotfixes => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryOptimizerHotfixes);
    /// <summary>Gets the QueryOptimizerHotfixesForSecondary property.</summary>
    public bool? QueryOptimizerHotfixesForSecondary => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryOptimizerHotfixesForSecondary);
    /// <summary>Gets the QueryStoreCaptureMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.QueryStoreCaptureMode QueryStoreCaptureMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.QueryStoreCaptureMode>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreCaptureMode);
    /// <summary>Gets the QueryStoreDesiredState property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.QueryStoreDesiredState QueryStoreDesiredState => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.QueryStoreDesiredState>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreDesiredState);
    /// <summary>Gets the QueryStoreFlushInterval property.</summary>
    public int QueryStoreFlushInterval => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreFlushInterval);
    /// <summary>Gets the QueryStoreIntervalLength property.</summary>
    public int QueryStoreIntervalLength => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreIntervalLength);
    /// <summary>Gets the QueryStoreMaxPlansPerQuery property.</summary>
    public int QueryStoreMaxPlansPerQuery => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreMaxPlansPerQuery);
    /// <summary>Gets the QueryStoreMaxStorageSize property.</summary>
    public int QueryStoreMaxStorageSize => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreMaxStorageSize);
    /// <summary>Gets the QueryStoreStaleQueryThreshold property.</summary>
    public int QueryStoreStaleQueryThreshold => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.QueryStoreStaleQueryThreshold);
    /// <summary>Gets the RecoveryMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.RecoveryMode RecoveryMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.RecoveryMode>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.RecoveryMode);
    /// <summary>Gets the RemoteDataEnabled property.</summary>
    public bool RemoteDataEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.RemoteDataEnabled);
    /// <summary>Gets the ServiceBrokerOption property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.ServiceBrokerOption ServiceBrokerOption => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.ServiceBrokerOption>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.ServiceBrokerOption);
    /// <summary>Gets the TargetRecoveryTimePeriod property.</summary>
    public int TargetRecoveryTimePeriod => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TargetRecoveryTimePeriod);
    /// <summary>Gets the TargetRecoveryTimeUnit property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.TimeUnit TargetRecoveryTimeUnit => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.TimeUnit>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TargetRecoveryTimeUnit);
    /// <summary>Gets the TemporalHistoryRetentionEnabled property.</summary>
    public bool TemporalHistoryRetentionEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TemporalHistoryRetentionEnabled);
    /// <summary>Gets the TwoDigitYearCutoff property.</summary>
    public short TwoDigitYearCutoff => SqlObject.GetProperty<short>(Microsoft.SqlServer.Dac.Model.DatabaseOptions.TwoDigitYearCutoff);
    ///<summary>
    /// Name: DefaultFilegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DefaultFilegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DefaultFilegroup);
    ///<summary>
    /// Name: DefaultFileStreamFilegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DefaultFileStreamFilegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseOptions.DefaultFileStreamFilegroup);
    ///<summary>
    /// Name: GenericDatabaseScopedConfigurationOptions. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> GenericDatabaseScopedConfigurationOptions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.DatabaseOptions.GenericDatabaseScopedConfigurationOptions);
}

public static class DatabaseOptionsExtensions
{
    public static DatabaseOptionsWrapper ToDatabaseOptions(this TSqlObject wrapper) => new DatabaseOptionsWrapper(wrapper);
}