// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx DefaultConstraint object.</summary>
public readonly struct DefaultConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DefaultConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )ObjectType.GetProperty(Microsoft.SqlServer.Dac.Model.DefaultConstraint.Expression);
    /// <summary>Gets the Disabled property.</summary>
    public bool Disabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DefaultConstraint.Disabled);
    /// <summary>Gets the WithValues property.</summary>
    public bool WithValues => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.DefaultConstraint.WithValues);
    ///<summary>
    /// Name: Host. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Host => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DefaultConstraint.Host);
    ///<summary>
    /// Name: TargetColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> TargetColumn => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DefaultConstraint.TargetColumn);
    ///<summary>
    /// Name: ExpressionDependencies. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ExpressionDependencies => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.DefaultConstraint.ExpressionDependencies);
}

public static class DefaultConstraintExtensions
{
    public static DefaultConstraintWrapper ToDefaultConstraint(this TSqlObject wrapper) => new DefaultConstraintWrapper(wrapper);
}