// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Default object.</summary>
public readonly struct DefaultWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public DefaultWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )ObjectType.GetProperty(Microsoft.SqlServer.Dac.Model.Default.Expression);
    ///<summary>
    /// Name: BoundObjects. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> BoundObjects => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Default.BoundObjects);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Default.Schema);
}

public static class DefaultExtensions
{
    public static DefaultWrapper ToDefault(this TSqlObject wrapper) => new DefaultWrapper(wrapper);
}