// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx EdgeConstraint object.</summary>
public readonly struct EdgeConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EdgeConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Disabled property.</summary>
    public bool Disabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.EdgeConstraint.Disabled);
    /// <summary>Gets the DeleteAction property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.ForeignKeyAction DeleteAction => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.ForeignKeyAction>(Microsoft.SqlServer.Dac.Model.EdgeConstraint.DeleteAction);
    ///<summary>
    /// Name: Host. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Host => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.EdgeConstraint.Host);
    ///<summary>
    /// Name: Clauses. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> Clauses => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.EdgeConstraint.Clauses);
}

public static class EdgeConstraintExtensions
{
    public static EdgeConstraintWrapper ToEdgeConstraint(this TSqlObject wrapper) => new EdgeConstraintWrapper(wrapper);
}