// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Endpoint object.</summary>
public readonly struct EndpointWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EndpointWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Payload property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.Payload Payload => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.Payload>(Microsoft.SqlServer.Dac.Model.Endpoint.Payload);
    /// <summary>Gets the Protocol property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.Protocol Protocol => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.Protocol>(Microsoft.SqlServer.Dac.Model.Endpoint.Protocol);
    /// <summary>Gets the State property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.State State => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.State>(Microsoft.SqlServer.Dac.Model.Endpoint.State);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Endpoint.Authorizer);
    ///<summary>
    /// Name: PayloadSpecifier. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> PayloadSpecifier => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Endpoint.PayloadSpecifier);
    ///<summary>
    /// Name: ProtocolSpecifier. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> ProtocolSpecifier => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Endpoint.ProtocolSpecifier);
}

public static class EndpointExtensions
{
    public static EndpointWrapper ToEndpoint(this TSqlObject wrapper) => new EndpointWrapper(wrapper);
}