// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx EventSession object.</summary>
public readonly struct EventSessionWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EventSessionWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the StartupState property.</summary>
    public bool StartupState => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.EventSession.StartupState);
    /// <summary>Gets the TrackCausality property.</summary>
    public bool TrackCausality => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.EventSession.TrackCausality);
    /// <summary>Gets the MaxDispatchLatency property.</summary>
    public int MaxDispatchLatency => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.EventSession.MaxDispatchLatency);
    /// <summary>Gets the MaxEventSizeUnit property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.MemoryUnit MaxEventSizeUnit => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.MemoryUnit>(Microsoft.SqlServer.Dac.Model.EventSession.MaxEventSizeUnit);
    /// <summary>Gets the MaxMemoryUnit property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.MemoryUnit MaxMemoryUnit => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.MemoryUnit>(Microsoft.SqlServer.Dac.Model.EventSession.MaxMemoryUnit);
    /// <summary>Gets the EventRetentionMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.EventRetentionMode EventRetentionMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.EventRetentionMode>(Microsoft.SqlServer.Dac.Model.EventSession.EventRetentionMode);
    /// <summary>Gets the MaxEventSize property.</summary>
    public int MaxEventSize => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.EventSession.MaxEventSize);
    /// <summary>Gets the MaxMemory property.</summary>
    public int MaxMemory => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.EventSession.MaxMemory);
    /// <summary>Gets the MemoryPartitionMode property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.MemoryPartitionMode MemoryPartitionMode => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.MemoryPartitionMode>(Microsoft.SqlServer.Dac.Model.EventSession.MemoryPartitionMode);
    /// <summary>Gets the SessionScope property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.EventSessionScope SessionScope => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.EventSessionScope>(Microsoft.SqlServer.Dac.Model.EventSession.SessionScope);
    ///<summary>
    /// Name: EventDefinitions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventDefinitions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.EventSession.EventDefinitions);
    ///<summary>
    /// Name: EventTargets. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventTargets => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.EventSession.EventTargets);
}

public static class EventSessionExtensions
{
    public static EventSessionWrapper ToEventSession(this TSqlObject wrapper) => new EventSessionWrapper(wrapper);
}