// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx EventTypeSpecifier object.</summary>
public readonly struct EventTypeSpecifierWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EventTypeSpecifierWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the EventType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.EventType EventType => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.EventType>(Microsoft.SqlServer.Dac.Model.EventTypeSpecifier.EventType);
    /// <summary>Gets the Order property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.OrderRestriction Order => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.OrderRestriction>(Microsoft.SqlServer.Dac.Model.EventTypeSpecifier.Order);
}

public static class EventTypeSpecifierExtensions
{
    public static EventTypeSpecifierWrapper ToEventTypeSpecifier(this TSqlObject wrapper) => new EventTypeSpecifierWrapper(wrapper);
}