// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx EventGroup object.</summary>
public readonly struct EventGroupWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EventGroupWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Group property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.EventGroupType Group => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.EventGroupType>(Microsoft.SqlServer.Dac.Model.EventGroup.Group);
}

public static class EventGroupExtensions
{
    public static EventGroupWrapper ToEventGroup(this TSqlObject wrapper) => new EventGroupWrapper(wrapper);
}