// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx EventSessionAction object.</summary>
public readonly struct EventSessionActionWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public EventSessionActionWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the ActionName property.</summary>
    public string? ActionName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.EventSessionAction.ActionName);
    /// <summary>Gets the EventModuleGuid property.</summary>
    public string? EventModuleGuid => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.EventSessionAction.EventModuleGuid);
    /// <summary>Gets the EventPackageName property.</summary>
    public string? EventPackageName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.EventSessionAction.EventPackageName);
}

public static class EventSessionActionExtensions
{
    public static EventSessionActionWrapper ToEventSessionAction(this TSqlObject wrapper) => new EventSessionActionWrapper(wrapper);
}