// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExternalLibrary object.</summary>
public readonly struct ExternalLibraryWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExternalLibraryWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Language property.</summary>
    public string? Language => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalLibrary.Language);
    /// <summary>Gets the LibraryName property.</summary>
    public string? LibraryName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalLibrary.LibraryName);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalLibrary.Authorizer);
    ///<summary>
    /// Name: ExternalLibraryFiles. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> ExternalLibraryFiles => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalLibrary.ExternalLibraryFiles);
}

public static class ExternalLibraryExtensions
{
    public static ExternalLibraryWrapper ToExternalLibrary(this TSqlObject wrapper) => new ExternalLibraryWrapper(wrapper);
}