// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExternalLanguage object.</summary>
public readonly struct ExternalLanguageWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExternalLanguageWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the LanguageName property.</summary>
    public string? LanguageName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalLanguage.LanguageName);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalLanguage.Authorizer);
    ///<summary>
    /// Name: ExternalLanguageFiles. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> ExternalLanguageFiles => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalLanguage.ExternalLanguageFiles);
}

public static class ExternalLanguageExtensions
{
    public static ExternalLanguageWrapper ToExternalLanguage(this TSqlObject wrapper) => new ExternalLanguageWrapper(wrapper);
}