// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExternalStreamingJob object.</summary>
public readonly struct ExternalStreamingJobWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExternalStreamingJobWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Statement property.</summary>
    public string? Statement => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalStreamingJob.Statement);
}

public static class ExternalStreamingJobExtensions
{
    public static ExternalStreamingJobWrapper ToExternalStreamingJob(this TSqlObject wrapper) => new ExternalStreamingJobWrapper(wrapper);
}