// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExternalModel object.</summary>
public readonly struct ExternalModelWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExternalModelWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Location property.</summary>
    public string? Location => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalModel.Location);
    /// <summary>Gets the ApiFormat property.</summary>
    public string? ApiFormat => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalModel.ApiFormat);
    /// <summary>Gets the ModelType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.ExternalModelType ModelType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.ExternalModelType>(Microsoft.SqlServer.Dac.Model.ExternalModel.ModelType);
    /// <summary>Gets the ModelNameExternal property.</summary>
    public string? ModelNameExternal => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalModel.ModelNameExternal);
    /// <summary>Gets the Parameters property.</summary>
    public string? Parameters => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalModel.Parameters);
    /// <summary>Gets the LocalRuntimePath property.</summary>
    public string? LocalRuntimePath => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalModel.LocalRuntimePath);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalModel.Authorizer);
    ///<summary>
    /// Name: Credential. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Credential => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExternalModel.Credential);
}

public static class ExternalModelExtensions
{
    public static ExternalModelWrapper ToExternalModel(this TSqlObject wrapper) => new ExternalModelWrapper(wrapper);
}