// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExtendedProcedure object.</summary>
public readonly struct ExtendedProcedureWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExtendedProcedureWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the ExeccuteAsCaller property.</summary>
    public bool ExeccuteAsCaller => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.ExeccuteAsCaller);
    /// <summary>Gets the WithEncryption property.</summary>
    public bool WithEncryption => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.WithEncryption);
    /// <summary>Gets the ExecuteAsOwner property.</summary>
    public bool ExecuteAsOwner => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.ExecuteAsOwner);
    /// <summary>Gets the ExecuteAsSelf property.</summary>
    public bool ExecuteAsSelf => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.ExecuteAsSelf);
    ///<summary>
    /// Name: Login. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Login => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.Login);
    ///<summary>
    /// Name: Parameters. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> Parameters => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.Parameters);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.Schema);
    ///<summary>
    /// Name: User. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> User => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.ExtendedProcedure.User);
}

public static class ExtendedProcedureExtensions
{
    public static ExtendedProcedureWrapper ToExtendedProcedure(this TSqlObject wrapper) => new ExtendedProcedureWrapper(wrapper);
}