// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ExternalLibraryFile object.</summary>
public readonly struct ExternalLibraryFileWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ExternalLibraryFileWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Content property.</summary>
    public string? Content => (string? )SqlObject.GetProperty(Microsoft.SqlServer.Dac.Model.ExternalLibraryFile.Content);
    /// <summary>Gets the Platform property.</summary>
    public string? Platform => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalLibraryFile.Platform);
    /// <summary>Gets the Path property.</summary>
    public string? Path => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ExternalLibraryFile.Path);
}

public static class ExternalLibraryFileExtensions
{
    public static ExternalLibraryFileWrapper ToExternalLibraryFile(this TSqlObject wrapper) => new ExternalLibraryFileWrapper(wrapper);
}