// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx FullTextCatalog object.</summary>
public readonly struct FullTextCatalogWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public FullTextCatalogWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the AccentSensitivity property.</summary>
    public bool? AccentSensitivity => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.FullTextCatalog.AccentSensitivity);
    /// <summary>Gets the IsDefault property.</summary>
    public bool IsDefault => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.FullTextCatalog.IsDefault);
    /// <summary>Gets the Path property.</summary>
    public string? Path => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.FullTextCatalog.Path);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.FullTextCatalog.Authorizer);
    ///<summary>
    /// Name: Filegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Filegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.FullTextCatalog.Filegroup);
}

public static class FullTextCatalogExtensions
{
    public static FullTextCatalogWrapper ToFullTextCatalog(this TSqlObject wrapper) => new FullTextCatalogWrapper(wrapper);
}