// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx LinkedServer object.</summary>
public readonly struct LinkedServerWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public LinkedServerWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the CollationCompatible property.</summary>
    public bool CollationCompatible => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.CollationCompatible);
    /// <summary>Gets the DataAccess property.</summary>
    public bool DataAccess => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.DataAccess);
    /// <summary>Gets the LazySchemaValidationEnabled property.</summary>
    public bool LazySchemaValidationEnabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.LazySchemaValidationEnabled);
    /// <summary>Gets the RemoteProcTransactionPromotionEnabled property.</summary>
    public bool RemoteProcTransactionPromotionEnabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.RemoteProcTransactionPromotionEnabled);
    /// <summary>Gets the RpcEnabled property.</summary>
    public bool RpcEnabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.RpcEnabled);
    /// <summary>Gets the RpcOutEnabled property.</summary>
    public bool RpcOutEnabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.RpcOutEnabled);
    /// <summary>Gets the ProviderName property.</summary>
    public string? ProviderName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.ProviderName);
    /// <summary>Gets the Catalog property.</summary>
    public string? Catalog => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.Catalog);
    /// <summary>Gets the CollationName property.</summary>
    public string? CollationName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.CollationName);
    /// <summary>Gets the ConnectTimeout property.</summary>
    public int ConnectTimeout => ObjectType.GetProperty<int>(Microsoft.SqlServer.Dac.Model.LinkedServer.ConnectTimeout);
    /// <summary>Gets the DataSource property.</summary>
    public string? DataSource => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.DataSource);
    /// <summary>Gets the IsDistributor property.</summary>
    public bool IsDistributor => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.IsDistributor);
    /// <summary>Gets the IsPublisher property.</summary>
    public bool IsPublisher => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.IsPublisher);
    /// <summary>Gets the IsSubscriber property.</summary>
    public bool IsSubscriber => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.IsSubscriber);
    /// <summary>Gets the Location property.</summary>
    public string? Location => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.Location);
    /// <summary>Gets the ProductName property.</summary>
    public string? ProductName => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.ProductName);
    /// <summary>Gets the ProviderString property.</summary>
    public string? ProviderString => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.LinkedServer.ProviderString);
    /// <summary>Gets the QueryTimeout property.</summary>
    public int QueryTimeout => ObjectType.GetProperty<int>(Microsoft.SqlServer.Dac.Model.LinkedServer.QueryTimeout);
    /// <summary>Gets the UseRemoteCollation property.</summary>
    public bool UseRemoteCollation => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.LinkedServer.UseRemoteCollation);
}

public static class LinkedServerExtensions
{
    public static LinkedServerWrapper ToLinkedServer(this TSqlObject wrapper) => new LinkedServerWrapper(wrapper);
}