// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx MessageType object.</summary>
public readonly struct MessageTypeWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public MessageTypeWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the ValidationMethod property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.ValidationMethod ValidationMethod => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.ValidationMethod>(Microsoft.SqlServer.Dac.Model.MessageType.ValidationMethod);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.MessageType.Authorizer);
    ///<summary>
    /// Name: XmlSchemaCollection. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> XmlSchemaCollection => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.MessageType.XmlSchemaCollection);
}

public static class MessageTypeExtensions
{
    public static MessageTypeWrapper ToMessageType(this TSqlObject wrapper) => new MessageTypeWrapper(wrapper);
}