// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx PartitionFunction object.</summary>
public readonly struct PartitionFunctionWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public PartitionFunctionWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Range property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.PartitionRange Range => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.PartitionRange>(Microsoft.SqlServer.Dac.Model.PartitionFunction.Range);
    ///<summary>
    /// Name: ParameterType. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ParameterType => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.PartitionFunction.ParameterType);
    ///<summary>
    /// Name: BoundaryValues. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> BoundaryValues => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.PartitionFunction.BoundaryValues);
}

public static class PartitionFunctionExtensions
{
    public static PartitionFunctionWrapper ToPartitionFunction(this TSqlObject wrapper) => new PartitionFunctionWrapper(wrapper);
}