// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx PartitionScheme object.</summary>
public readonly struct PartitionSchemeWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public PartitionSchemeWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the AllToOneFilegroup property.</summary>
    public bool AllToOneFilegroup => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PartitionScheme.AllToOneFilegroup);
    ///<summary>
    /// Name: Filegroups. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Filegroups => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PartitionScheme.Filegroups);
    ///<summary>
    /// Name: PartitionFunction. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionFunction => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PartitionScheme.PartitionFunction);
}

public static class PartitionSchemeExtensions
{
    public static PartitionSchemeWrapper ToPartitionScheme(this TSqlObject wrapper) => new PartitionSchemeWrapper(wrapper);
}