// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx PartitionValue object.</summary>
public readonly struct PartitionValueWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public PartitionValueWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )SqlObject.GetProperty(Microsoft.SqlServer.Dac.Model.PartitionValue.Expression);
    ///<summary>
    /// Name: ExpressionDependencies. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ExpressionDependencies => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.PartitionValue.ExpressionDependencies);
}

public static class PartitionValueExtensions
{
    public static PartitionValueWrapper ToPartitionValue(this TSqlObject wrapper) => new PartitionValueWrapper(wrapper);
}