// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx PrimaryKeyConstraint object.</summary>
public readonly struct PrimaryKeyConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public PrimaryKeyConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the AllowPageLocks property.</summary>
    public bool AllowPageLocks => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.AllowPageLocks);
    /// <summary>Gets the AllowRowLocks property.</summary>
    public bool AllowRowLocks => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.AllowRowLocks);
    /// <summary>Gets the IgnoreDuplicateKey property.</summary>
    public bool IgnoreDuplicateKey => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.IgnoreDuplicateKey);
    /// <summary>Gets the RecomputeStatistics property.</summary>
    public bool RecomputeStatistics => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.RecomputeStatistics);
    /// <summary>Gets the Clustered property.</summary>
    public bool Clustered => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Clustered);
    /// <summary>Gets the Disabled property.</summary>
    public bool Disabled => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Disabled);
    /// <summary>Gets the FileStreamNull property.</summary>
    public bool? FileStreamNull => ObjectType.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.FileStreamNull);
    /// <summary>Gets the WithPadIndex property.</summary>
    public bool WithPadIndex => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.WithPadIndex);
    /// <summary>Gets the Hash property.</summary>
    public bool Hash => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Hash);
    /// <summary>Gets the OptimizeForSequentialKey property.</summary>
    public bool OptimizeForSequentialKey => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.OptimizeForSequentialKey);
    /// <summary>Gets the AutoCreated property.</summary>
    public bool AutoCreated => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.AutoCreated);
    /// <summary>Gets the BucketCount property.</summary>
    public int? BucketCount => ObjectType.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.BucketCount);
    /// <summary>Gets the DoIncrementalStatistics property.</summary>
    public bool DoIncrementalStatistics => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.DoIncrementalStatistics);
    /// <summary>Gets the FillFactor property.</summary>
    public int? FillFactor => ObjectType.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.FillFactor);
    /// <summary>Gets the Online property.</summary>
    public bool? Online => ObjectType.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Online);
    ///<summary>
    /// Name: Host. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Host => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Host);
    ///<summary>
    /// Name: Columns. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Columns => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Columns);
    ///<summary>
    /// Name: DataCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> DataCompressionOptions => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.DataCompressionOptions);
    ///<summary>
    /// Name: Filegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Filegroup => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.Filegroup);
    ///<summary>
    /// Name: FileStreamFilegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> FileStreamFilegroup => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.FileStreamFilegroup);
    ///<summary>
    /// Name: FileStreamPartitionScheme. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> FileStreamPartitionScheme => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.FileStreamPartitionScheme);
    ///<summary>
    /// Name: PartitionColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionColumn => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.PartitionColumn);
    ///<summary>
    /// Name: PartitionScheme. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionScheme => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.PartitionScheme);
    ///<summary>
    /// Name: XmlCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> XmlCompressionOptions => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.PrimaryKeyConstraint.XmlCompressionOptions);
}

public static class PrimaryKeyConstraintExtensions
{
    public static PrimaryKeyConstraintWrapper ToPrimaryKeyConstraint(this TSqlObject wrapper) => new PrimaryKeyConstraintWrapper(wrapper);
}