// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx PromotedNodePathForSqlType object.</summary>
public readonly struct PromotedNodePathForSqlTypeWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public PromotedNodePathForSqlTypeWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Scale property.</summary>
    public int Scale => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.Scale);
    /// <summary>Gets the Precision property.</summary>
    public int Precision => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.Precision);
    /// <summary>Gets the Length property.</summary>
    public int Length => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.Length);
    /// <summary>Gets the IsMax property.</summary>
    public bool IsMax => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.IsMax);
    /// <summary>Gets the IsSingleton property.</summary>
    public bool IsSingleton => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.IsSingleton);
    /// <summary>Gets the NodePath property.</summary>
    public string? NodePath => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.NodePath);
    ///<summary>
    /// Name: DataType. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DataType => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.PromotedNodePathForSqlType.DataType);
}

public static class PromotedNodePathForSqlTypeExtensions
{
    public static PromotedNodePathForSqlTypeWrapper ToPromotedNodePathForSqlType(this TSqlObject wrapper) => new PromotedNodePathForSqlTypeWrapper(wrapper);
}