// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx QueueEventNotification object.</summary>
public readonly struct QueueEventNotificationWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public QueueEventNotificationWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the WithFanIn property.</summary>
    public bool WithFanIn => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.QueueEventNotification.WithFanIn);
    /// <summary>Gets the BrokerService property.</summary>
    public string? BrokerService => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.QueueEventNotification.BrokerService);
    /// <summary>Gets the BrokerInstanceSpecifier property.</summary>
    public string? BrokerInstanceSpecifier => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.QueueEventNotification.BrokerInstanceSpecifier);
    ///<summary>
    /// Name: EventGroup. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventGroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.QueueEventNotification.EventGroup);
    ///<summary>
    /// Name: EventType. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventType => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.QueueEventNotification.EventType);
    ///<summary>
    /// Name: Queue. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Queue => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.QueueEventNotification.Queue);
}

public static class QueueEventNotificationExtensions
{
    public static QueueEventNotificationWrapper ToQueueEventNotification(this TSqlObject wrapper) => new QueueEventNotificationWrapper(wrapper);
}