// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx RemoteServiceBinding object.</summary>
public readonly struct RemoteServiceBindingWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public RemoteServiceBindingWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Anonymous property.</summary>
    public bool Anonymous => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.RemoteServiceBinding.Anonymous);
    /// <summary>Gets the Service property.</summary>
    public string? Service => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.RemoteServiceBinding.Service);
    ///<summary>
    /// Name: User. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> User => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.RemoteServiceBinding.User);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.RemoteServiceBinding.Authorizer);
}

public static class RemoteServiceBindingExtensions
{
    public static RemoteServiceBindingWrapper ToRemoteServiceBinding(this TSqlObject wrapper) => new RemoteServiceBindingWrapper(wrapper);
}