// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx SearchPropertyList object.</summary>
public readonly struct SearchPropertyListWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SearchPropertyListWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.SearchPropertyList.Authorizer);
}

public static class SearchPropertyListExtensions
{
    public static SearchPropertyListWrapper ToSearchPropertyList(this TSqlObject wrapper) => new SearchPropertyListWrapper(wrapper);
}