// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ServerEventNotification object.</summary>
public readonly struct ServerEventNotificationWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ServerEventNotificationWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the WithFanIn property.</summary>
    public bool WithFanIn => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerEventNotification.WithFanIn);
    /// <summary>Gets the BrokerService property.</summary>
    public string? BrokerService => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ServerEventNotification.BrokerService);
    /// <summary>Gets the BrokerInstanceSpecifier property.</summary>
    public string? BrokerInstanceSpecifier => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ServerEventNotification.BrokerInstanceSpecifier);
    ///<summary>
    /// Name: EventGroup. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventGroup => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.ServerEventNotification.EventGroup);
    ///<summary>
    /// Name: EventType. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> EventType => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.ServerEventNotification.EventType);
}

public static class ServerEventNotificationExtensions
{
    public static ServerEventNotificationWrapper ToServerEventNotification(this TSqlObject wrapper) => new ServerEventNotificationWrapper(wrapper);
}