// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ServerAudit object.</summary>
public readonly struct ServerAuditWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ServerAuditWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Disabled property.</summary>
    public bool Disabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerAudit.Disabled);
    /// <summary>Gets the ReserveDiskSpace property.</summary>
    public bool ReserveDiskSpace => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerAudit.ReserveDiskSpace);
    /// <summary>Gets the UnlimitedFileSize property.</summary>
    public bool UnlimitedFileSize => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerAudit.UnlimitedFileSize);
    /// <summary>Gets the UnlimitedMaxRolloverFiles property.</summary>
    public bool UnlimitedMaxRolloverFiles => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerAudit.UnlimitedMaxRolloverFiles);
    /// <summary>Gets the OnFailure property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.FailureAction OnFailure => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.FailureAction>(Microsoft.SqlServer.Dac.Model.ServerAudit.OnFailure);
    /// <summary>Gets the PredicateExpression property.</summary>
    public string? PredicateExpression => (string? )SqlObject.GetProperty(Microsoft.SqlServer.Dac.Model.ServerAudit.PredicateExpression);
    /// <summary>Gets the AuditGuid property.</summary>
    public string? AuditGuid => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ServerAudit.AuditGuid);
    /// <summary>Gets the AuditTarget property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.AuditTarget AuditTarget => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.AuditTarget>(Microsoft.SqlServer.Dac.Model.ServerAudit.AuditTarget);
    /// <summary>Gets the FilePath property.</summary>
    public string? FilePath => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ServerAudit.FilePath);
    /// <summary>Gets the IsOperatorAudit property.</summary>
    public bool IsOperatorAudit => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.ServerAudit.IsOperatorAudit);
    /// <summary>Gets the MaxFiles property.</summary>
    public int? MaxFiles => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.ServerAudit.MaxFiles);
    /// <summary>Gets the MaxRolloverFiles property.</summary>
    public int? MaxRolloverFiles => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.ServerAudit.MaxRolloverFiles);
    /// <summary>Gets the MaxSize property.</summary>
    public int? MaxSize => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.ServerAudit.MaxSize);
    /// <summary>Gets the MaxSizeUnit property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.MemoryUnit MaxSizeUnit => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.MemoryUnit>(Microsoft.SqlServer.Dac.Model.ServerAudit.MaxSizeUnit);
    /// <summary>Gets the Path property.</summary>
    public string? Path => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.ServerAudit.Path);
    /// <summary>Gets the QueueDelay property.</summary>
    public int QueueDelay => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.ServerAudit.QueueDelay);
    /// <summary>Gets the RetentionDays property.</summary>
    public int RetentionDays => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.ServerAudit.RetentionDays);
}

public static class ServerAuditExtensions
{
    public static ServerAuditWrapper ToServerAudit(this TSqlObject wrapper) => new ServerAuditWrapper(wrapper);
}