// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx ServerOptions object.</summary>
public readonly struct ServerOptionsWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ServerOptionsWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
}

public static class ServerOptionsExtensions
{
    public static ServerOptionsWrapper ToServerOptions(this TSqlObject wrapper) => new ServerOptionsWrapper(wrapper);
}