// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Service object.</summary>
public readonly struct ServiceWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public ServiceWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the UseDefaultContract property.</summary>
    public bool UseDefaultContract => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Service.UseDefaultContract);
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Service.Authorizer);
    ///<summary>
    /// Name: Contracts. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Contracts => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Service.Contracts);
    ///<summary>
    /// Name: Queue. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Queue => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Service.Queue);
}

public static class ServiceExtensions
{
    public static ServiceWrapper ToService(this TSqlObject wrapper) => new ServiceWrapper(wrapper);
}