// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx SignatureEncryptionMechanism object.</summary>
public readonly struct SignatureEncryptionMechanismWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SignatureEncryptionMechanismWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Password property.</summary>
    public string? Password => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SignatureEncryptionMechanism.Password);
    /// <summary>Gets the SignedBlob property.</summary>
    public string? SignedBlob => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SignatureEncryptionMechanism.SignedBlob);
    ///<summary>
    /// Name: AsymmetricKey. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> AsymmetricKey => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.SignatureEncryptionMechanism.AsymmetricKey);
    ///<summary>
    /// Name: Certificate. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Certificate => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.SignatureEncryptionMechanism.Certificate);
}

public static class SignatureEncryptionMechanismExtensions
{
    public static SignatureEncryptionMechanismWrapper ToSignatureEncryptionMechanism(this TSqlObject wrapper) => new SignatureEncryptionMechanismWrapper(wrapper);
}