// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx SoapLanguageSpecifier object.</summary>
public readonly struct SoapLanguageSpecifierWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SoapLanguageSpecifierWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the BatchesEnabled property.</summary>
    public bool BatchesEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.BatchesEnabled);
    /// <summary>Gets the SessionsEnabled property.</summary>
    public bool SessionsEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.SessionsEnabled);
    /// <summary>Gets the SessionTimeoutNever property.</summary>
    public bool SessionTimeoutNever => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.SessionTimeoutNever);
    /// <summary>Gets the CharacterSet property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.CharacterSet CharacterSet => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.CharacterSet>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.CharacterSet);
    /// <summary>Gets the DatabaseName property.</summary>
    public string? DatabaseName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.DatabaseName);
    /// <summary>Gets the HeaderLimit property.</summary>
    public int HeaderLimit => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.HeaderLimit);
    /// <summary>Gets the IsDefaultDatabase property.</summary>
    public bool IsDefaultDatabase => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.IsDefaultDatabase);
    /// <summary>Gets the IsDefaultNamespace property.</summary>
    public bool IsDefaultNamespace => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.IsDefaultNamespace);
    /// <summary>Gets the IsDefaultWsdlSpName property.</summary>
    public bool IsDefaultWsdlSpName => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.IsDefaultWsdlSpName);
    /// <summary>Gets the LoginType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SoapLoginType LoginType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.SoapLoginType>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.LoginType);
    /// <summary>Gets the Namespace property.</summary>
    public string? Namespace => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.Namespace);
    /// <summary>Gets the SchemaType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SoapSchema SchemaType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.SoapSchema>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.SchemaType);
    /// <summary>Gets the SessionTimeout property.</summary>
    public int SessionTimeout => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.SessionTimeout);
    /// <summary>Gets the WsdlSpName property.</summary>
    public string? WsdlSpName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.WsdlSpName);
    ///<summary>
    /// Name: WebMethods. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> WebMethods => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.SoapLanguageSpecifier.WebMethods);
}

public static class SoapLanguageSpecifierExtensions
{
    public static SoapLanguageSpecifierWrapper ToSoapLanguageSpecifier(this TSqlObject wrapper) => new SoapLanguageSpecifierWrapper(wrapper);
}