// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx SoapMethodSpecification object.</summary>
public readonly struct SoapMethodSpecificationWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SoapMethodSpecificationWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the SchemaType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SoapSchema SchemaType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.SoapSchema>(Microsoft.SqlServer.Dac.Model.SoapMethodSpecification.SchemaType);
    /// <summary>Gets the Format property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SoapFormat Format => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.SoapFormat>(Microsoft.SqlServer.Dac.Model.SoapMethodSpecification.Format);
    /// <summary>Gets the WebMethodAlias property.</summary>
    public string? WebMethodAlias => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SoapMethodSpecification.WebMethodAlias);
    /// <summary>Gets the WebMethodNamespace property.</summary>
    public string? WebMethodNamespace => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SoapMethodSpecification.WebMethodNamespace);
    ///<summary>
    /// Name: RelatedMethod. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> RelatedMethod => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.SoapMethodSpecification.RelatedMethod);
}

public static class SoapMethodSpecificationExtensions
{
    public static SoapMethodSpecificationWrapper ToSoapMethodSpecification(this TSqlObject wrapper) => new SoapMethodSpecificationWrapper(wrapper);
}