// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx SymmetricKeyPassword object.</summary>
public readonly struct SymmetricKeyPasswordWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SymmetricKeyPasswordWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Password property.</summary>
    public string? Password => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.SymmetricKeyPassword.Password);
}

public static class SymmetricKeyPasswordExtensions
{
    public static SymmetricKeyPasswordWrapper ToSymmetricKeyPassword(this TSqlObject wrapper) => new SymmetricKeyPasswordWrapper(wrapper);
}