// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Synonym object.</summary>
public readonly struct SynonymWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public SynonymWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the ForObjectName property.</summary>
    public string? ForObjectName => (string? )ObjectType.GetProperty(Microsoft.SqlServer.Dac.Model.Synonym.ForObjectName);
    ///<summary>
    /// Name: ForObject. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ForObject => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Synonym.ForObject);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.Synonym.Schema);
}

public static class SynonymExtensions
{
    public static SynonymWrapper ToSynonym(this TSqlObject wrapper) => new SynonymWrapper(wrapper);
}