// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx TableTypeCheckConstraint object.</summary>
public readonly struct TableTypeCheckConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public TableTypeCheckConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )ObjectType.GetProperty(Microsoft.SqlServer.Dac.Model.TableTypeCheckConstraint.Expression);
    ///<summary>
    /// Name: ExpressionDependencies. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ExpressionDependencies => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.TableTypeCheckConstraint.ExpressionDependencies);
}

public static class TableTypeCheckConstraintExtensions
{
    public static TableTypeCheckConstraintWrapper ToTableTypeCheckConstraint(this TSqlObject wrapper) => new TableTypeCheckConstraintWrapper(wrapper);
}