// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx TableTypeUniqueConstraint object.</summary>
public readonly struct TableTypeUniqueConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public TableTypeUniqueConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the IgnoreDuplicateKey property.</summary>
    public bool IgnoreDuplicateKey => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.TableTypeUniqueConstraint.IgnoreDuplicateKey);
    /// <summary>Gets the Clustered property.</summary>
    public bool Clustered => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.TableTypeUniqueConstraint.Clustered);
    /// <summary>Gets the Hash property.</summary>
    public bool Hash => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.TableTypeUniqueConstraint.Hash);
    /// <summary>Gets the BucketCount property.</summary>
    public int? BucketCount => ObjectType.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.TableTypeUniqueConstraint.BucketCount);
    ///<summary>
    /// Name: Columns. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Columns => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.TableTypeUniqueConstraint.Columns);
}

public static class TableTypeUniqueConstraintExtensions
{
    public static TableTypeUniqueConstraintWrapper ToTableTypeUniqueConstraint(this TSqlObject wrapper) => new TableTypeUniqueConstraintWrapper(wrapper);
}