// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx TableTypeDefaultConstraint object.</summary>
public readonly struct TableTypeDefaultConstraintWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public TableTypeDefaultConstraintWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )ObjectType.GetProperty(Microsoft.SqlServer.Dac.Model.TableTypeDefaultConstraint.Expression);
    ///<summary>
    /// Name: TargetColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> TargetColumn => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.TableTypeDefaultConstraint.TargetColumn);
    ///<summary>
    /// Name: ExpressionDependencies. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ExpressionDependencies => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.TableTypeDefaultConstraint.ExpressionDependencies);
}

public static class TableTypeDefaultConstraintExtensions
{
    public static TableTypeDefaultConstraintWrapper ToTableTypeDefaultConstraint(this TSqlObject wrapper) => new TableTypeDefaultConstraintWrapper(wrapper);
}