// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx Table object.</summary>
public readonly struct TableWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public TableWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the AnsiNullsOn property.</summary>
    public bool? AnsiNullsOn => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.Table.AnsiNullsOn);
    /// <summary>Gets the ChangeDataCaptureEnabled property.</summary>
    public bool ChangeDataCaptureEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.ChangeDataCaptureEnabled);
    /// <summary>Gets the ChangeTrackingEnabled property.</summary>
    public bool ChangeTrackingEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.ChangeTrackingEnabled);
    /// <summary>Gets the FileStreamNull property.</summary>
    public bool? FileStreamNull => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.Table.FileStreamNull);
    /// <summary>Gets the LargeValueTypesOutOfRow property.</summary>
    public bool LargeValueTypesOutOfRow => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.LargeValueTypesOutOfRow);
    /// <summary>Gets the QuotedIdentifierOn property.</summary>
    public bool? QuotedIdentifierOn => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.Table.QuotedIdentifierOn);
    /// <summary>Gets the TableLockOnBulkLoad property.</summary>
    public bool TableLockOnBulkLoad => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.TableLockOnBulkLoad);
    /// <summary>Gets the TrackColumnsUpdated property.</summary>
    public bool TrackColumnsUpdated => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.TrackColumnsUpdated);
    /// <summary>Gets the VardecimalStorageFormatEnabled property.</summary>
    public bool VardecimalStorageFormatEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.VardecimalStorageFormatEnabled);
    /// <summary>Gets the MemoryOptimized property.</summary>
    public bool MemoryOptimized => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.MemoryOptimized);
    /// <summary>Gets the DistributionPolicyType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.TableDistributionPolicyType DistributionPolicyType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.TableDistributionPolicyType>(Microsoft.SqlServer.Dac.Model.Table.DistributionPolicyType);
    /// <summary>Gets the RowCount property.</summary>
    public long? RowCount => SqlObject.GetProperty<long?>(Microsoft.SqlServer.Dac.Model.Table.RowCount);
    /// <summary>Gets the DataSize property.</summary>
    public double? DataSize => SqlObject.GetProperty<double?>(Microsoft.SqlServer.Dac.Model.Table.DataSize);
    /// <summary>Gets the IndexSize property.</summary>
    public double? IndexSize => SqlObject.GetProperty<double?>(Microsoft.SqlServer.Dac.Model.Table.IndexSize);
    /// <summary>Gets the DataPages property.</summary>
    public long? DataPages => SqlObject.GetProperty<long?>(Microsoft.SqlServer.Dac.Model.Table.DataPages);
    /// <summary>Gets the UsedPages property.</summary>
    public long? UsedPages => SqlObject.GetProperty<long?>(Microsoft.SqlServer.Dac.Model.Table.UsedPages);
    /// <summary>Gets the Durability property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.Durability Durability => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.Durability>(Microsoft.SqlServer.Dac.Model.Table.Durability);
    /// <summary>Gets the IsAutoGeneratedHistoryTable property.</summary>
    public bool IsAutoGeneratedHistoryTable => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.IsAutoGeneratedHistoryTable);
    /// <summary>Gets the IsDroppedLedgerTable property.</summary>
    public bool IsDroppedLedgerTable => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.IsDroppedLedgerTable);
    /// <summary>Gets the IsEdge property.</summary>
    public bool IsEdge => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.IsEdge);
    /// <summary>Gets the IsNode property.</summary>
    public bool IsNode => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.IsNode);
    /// <summary>Gets the IsReplicated property.</summary>
    public bool IsReplicated => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.IsReplicated);
    /// <summary>Gets the LedgerHistoryTableName property.</summary>
    public string? LedgerHistoryTableName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerHistoryTableName);
    /// <summary>Gets the LedgerHistoryTableSchemaName property.</summary>
    public string? LedgerHistoryTableSchemaName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerHistoryTableSchemaName);
    /// <summary>Gets the LedgerType property.</summary>
    public int LedgerType => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.Table.LedgerType);
    /// <summary>Gets the LedgerViewName property.</summary>
    public string? LedgerViewName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewName);
    /// <summary>Gets the LedgerViewOperationTypeColumnName property.</summary>
    public string? LedgerViewOperationTypeColumnName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewOperationTypeColumnName);
    /// <summary>Gets the LedgerViewOperationTypeDescColumnName property.</summary>
    public string? LedgerViewOperationTypeDescColumnName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewOperationTypeDescColumnName);
    /// <summary>Gets the LedgerViewSchemaName property.</summary>
    public string? LedgerViewSchemaName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewSchemaName);
    /// <summary>Gets the LedgerViewSequenceNumberColumnName property.</summary>
    public string? LedgerViewSequenceNumberColumnName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewSequenceNumberColumnName);
    /// <summary>Gets the LedgerViewTransactionIdColumnName property.</summary>
    public string? LedgerViewTransactionIdColumnName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.Table.LedgerViewTransactionIdColumnName);
    /// <summary>Gets the LockEscalation property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.LockEscalationMethod LockEscalation => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.LockEscalationMethod>(Microsoft.SqlServer.Dac.Model.Table.LockEscalation);
    /// <summary>Gets the QueryScript property.</summary>
    public string? QueryScript => (string? )SqlObject.GetProperty(Microsoft.SqlServer.Dac.Model.Table.QueryScript);
    /// <summary>Gets the RemoteDataEnabled property.</summary>
    public bool RemoteDataEnabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.Table.RemoteDataEnabled);
    /// <summary>Gets the RetentionUnit property.</summary>
    public int RetentionUnit => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.Table.RetentionUnit);
    /// <summary>Gets the RetentionValue property.</summary>
    public int RetentionValue => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.Table.RetentionValue);
    /// <summary>Gets the TextInRowSize property.</summary>
    public int TextInRowSize => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.Table.TextInRowSize);
    ///<summary>
    /// Name: DistributionColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DistributionColumn => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.DistributionColumn);
    ///<summary>
    /// Name: ClusterByColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> ClusterByColumn => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.ClusterByColumn);
    ///<summary>
    /// Name: Columns. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> Columns => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.Columns);
    ///<summary>
    /// Name: DataCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> DataCompressionOptions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.DataCompressionOptions);
    ///<summary>
    /// Name: DataRetention. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> DataRetention => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.DataRetention);
    ///<summary>
    /// Name: DynamicObjects. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> DynamicObjects => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.DynamicObjects);
    ///<summary>
    /// Name: Filegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Filegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.Filegroup);
    ///<summary>
    /// Name: FilegroupForTextImage. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> FilegroupForTextImage => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.FilegroupForTextImage);
    ///<summary>
    /// Name: FileStreamFilegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> FileStreamFilegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.FileStreamFilegroup);
    ///<summary>
    /// Name: FileStreamPartitionScheme. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> FileStreamPartitionScheme => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.FileStreamPartitionScheme);
    ///<summary>
    /// Name: PartitionColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionColumn => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.PartitionColumn);
    ///<summary>
    /// Name: PartitionScheme. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionScheme => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.PartitionScheme);
    ///<summary>
    /// Name: PartitionSpecification. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> PartitionSpecification => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.PartitionSpecification);
    ///<summary>
    /// Name: QueryDependencies. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> QueryDependencies => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.QueryDependencies);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.Schema);
    ///<summary>
    /// Name: TemporalSystemVersioningHistoryTable. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> TemporalSystemVersioningHistoryTable => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.TemporalSystemVersioningHistoryTable);
    ///<summary>
    /// Name: XmlCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> XmlCompressionOptions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.Table.XmlCompressionOptions);
}

public static class TableExtensions
{
    public static TableWrapper ToTable(this TSqlObject wrapper) => new TableWrapper(wrapper);
}