// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx User object.</summary>
public readonly struct UserWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public UserWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    /// <summary>Gets the WithoutLogin property.</summary>
    public bool WithoutLogin => ObjectType.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.User.WithoutLogin);
    /// <summary>Gets the AuthenticationType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.AuthenticationType AuthenticationType => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.AuthenticationType>(Microsoft.SqlServer.Dac.Model.User.AuthenticationType);
    /// <summary>Gets the DefaultLanguage property.</summary>
    public string? DefaultLanguage => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.DefaultLanguage);
    /// <summary>Gets the Password property.</summary>
    public string? Password => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.Password);
    /// <summary>Gets the Sid property.</summary>
    public string? Sid => ObjectType.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.Sid);
    /// <summary>Gets the UserType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.UserType UserType => ObjectType.GetProperty<global::Microsoft.SqlServer.Dac.Model.UserType>(Microsoft.SqlServer.Dac.Model.User.UserType);
    ///<summary>
    /// Name: AsymmetricKey. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> AsymmetricKey => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.User.AsymmetricKey);
    ///<summary>
    /// Name: Certificate. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Certificate => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.User.Certificate);
    ///<summary>
    /// Name: DefaultSchema. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DefaultSchema => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.User.DefaultSchema);
    ///<summary>
    /// Name: Login. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Login => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.User.Login);
}

public static class UserExtensions
{
    public static UserWrapper ToUser(this TSqlObject wrapper) => new UserWrapper(wrapper);
}