// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx UserDefinedType object.</summary>
public readonly struct UserDefinedTypeWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public UserDefinedTypeWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the ByteOrdered property.</summary>
    public bool? ByteOrdered => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.UserDefinedType.ByteOrdered);
    /// <summary>Gets the FixedLength property.</summary>
    public bool? FixedLength => SqlObject.GetProperty<bool?>(Microsoft.SqlServer.Dac.Model.UserDefinedType.FixedLength);
    /// <summary>Gets the ClassName property.</summary>
    public string? ClassName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.UserDefinedType.ClassName);
    /// <summary>Gets the Format property.</summary>
    public int Format => SqlObject.GetProperty<int>(Microsoft.SqlServer.Dac.Model.UserDefinedType.Format);
    /// <summary>Gets the MaxByteSize property.</summary>
    public int? MaxByteSize => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.UserDefinedType.MaxByteSize);
    /// <summary>Gets the ValidationMethodName property.</summary>
    public string? ValidationMethodName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.UserDefinedType.ValidationMethodName);
    ///<summary>
    /// Name: Assembly. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Assembly => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.UserDefinedType.Assembly);
    ///<summary>
    /// Name: Methods. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> Methods => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.UserDefinedType.Methods);
    ///<summary>
    /// Name: Properties. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> Properties => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.UserDefinedType.Properties);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.UserDefinedType.Schema);
}

public static class UserDefinedTypeExtensions
{
    public static UserDefinedTypeWrapper ToUserDefinedType(this TSqlObject wrapper) => new UserDefinedTypeWrapper(wrapper);
}