// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx UserDefinedServerRole object.</summary>
public readonly struct UserDefinedServerRoleWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject ObjectType;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public UserDefinedServerRoleWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => ObjectType = @object;
    public string FullName => ObjectType.Name.ToString();
    ///<summary>
    /// Name: Authorizer. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Authorizer => ObjectType.GetReferenced(Microsoft.SqlServer.Dac.Model.UserDefinedServerRole.Authorizer);
}

public static class UserDefinedServerRoleExtensions
{
    public static UserDefinedServerRoleWrapper ToUserDefinedServerRole(this TSqlObject wrapper) => new UserDefinedServerRoleWrapper(wrapper);
}