// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx User object.</summary>
public readonly struct UserWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public UserWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the WithoutLogin property.</summary>
    public bool WithoutLogin => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.User.WithoutLogin);
    /// <summary>Gets the AuthenticationType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.AuthenticationType AuthenticationType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.AuthenticationType>(Microsoft.SqlServer.Dac.Model.User.AuthenticationType);
    /// <summary>Gets the DefaultLanguage property.</summary>
    public string? DefaultLanguage => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.DefaultLanguage);
    /// <summary>Gets the Password property.</summary>
    public string? Password => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.Password);
    /// <summary>Gets the Sid property.</summary>
    public string? Sid => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.User.Sid);
    /// <summary>Gets the UserType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.UserType UserType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.UserType>(Microsoft.SqlServer.Dac.Model.User.UserType);
    ///<summary>
    /// Name: AsymmetricKey. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> AsymmetricKey => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.User.AsymmetricKey);
    ///<summary>
    /// Name: Certificate. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Certificate => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.User.Certificate);
    ///<summary>
    /// Name: DefaultSchema. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> DefaultSchema => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.User.DefaultSchema);
    ///<summary>
    /// Name: Login. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Login => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.User.Login);
}

public static class UserExtensions
{
    public static UserWrapper ToUser(this TSqlObject wrapper) => new UserWrapper(wrapper);
}