// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx WorkloadClassifier object.</summary>
public readonly struct WorkloadClassifierWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public WorkloadClassifierWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the EndTime property.</summary>
    public string? EndTime => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.EndTime);
    /// <summary>Gets the Importance property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.Degree Importance => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.Degree>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.Importance);
    /// <summary>Gets the MemberName property.</summary>
    public string? MemberName => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.MemberName);
    /// <summary>Gets the StartTime property.</summary>
    public string? StartTime => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.StartTime);
    /// <summary>Gets the WlmContext property.</summary>
    public string? WlmContext => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.WlmContext);
    /// <summary>Gets the WlmLabel property.</summary>
    public string? WlmLabel => SqlObject.GetProperty<string?>(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.WlmLabel);
    ///<summary>
    /// Name: WorkloadGroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> WorkloadGroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.WorkloadClassifier.WorkloadGroup);
}

public static class WorkloadClassifierExtensions
{
    public static WorkloadClassifierWrapper ToWorkloadClassifier(this TSqlObject wrapper) => new WorkloadClassifierWrapper(wrapper);
}