// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx XmlIndex object.</summary>
public readonly struct XmlIndexWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public XmlIndexWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the AllowPageLocks property.</summary>
    public bool AllowPageLocks => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.AllowPageLocks);
    /// <summary>Gets the AllowRowLocks property.</summary>
    public bool AllowRowLocks => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.AllowRowLocks);
    /// <summary>Gets the IgnoreDuplicateKey property.</summary>
    public bool IgnoreDuplicateKey => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.IgnoreDuplicateKey);
    /// <summary>Gets the RecomputeStatistics property.</summary>
    public bool RecomputeStatistics => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.RecomputeStatistics);
    /// <summary>Gets the Disabled property.</summary>
    public bool Disabled => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.Disabled);
    /// <summary>Gets the WithPadIndex property.</summary>
    public bool WithPadIndex => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.WithPadIndex);
    /// <summary>Gets the SecondaryXmlIndexType property.</summary>
    public global::Microsoft.SqlServer.Dac.Model.SecondaryXmlIndexType SecondaryXmlIndexType => SqlObject.GetProperty<global::Microsoft.SqlServer.Dac.Model.SecondaryXmlIndexType>(Microsoft.SqlServer.Dac.Model.XmlIndex.SecondaryXmlIndexType);
    /// <summary>Gets the DoIncrementalStatistics property.</summary>
    public bool DoIncrementalStatistics => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.DoIncrementalStatistics);
    /// <summary>Gets the FillFactor property.</summary>
    public int? FillFactor => SqlObject.GetProperty<int?>(Microsoft.SqlServer.Dac.Model.XmlIndex.FillFactor);
    /// <summary>Gets the IsPrimary property.</summary>
    public bool IsPrimary => SqlObject.GetProperty<bool>(Microsoft.SqlServer.Dac.Model.XmlIndex.IsPrimary);
    ///<summary>
    /// Name: PrimaryXmlIndex. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PrimaryXmlIndex => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.PrimaryXmlIndex);
    ///<summary>
    /// Name: Column. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Column => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.Column);
    ///<summary>
    /// Name: DataCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> DataCompressionOptions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.DataCompressionOptions);
    ///<summary>
    /// Name: Filegroup. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> Filegroup => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.Filegroup);
    ///<summary>
    /// Name: IndexedObject. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> IndexedObject => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.IndexedObject);
    ///<summary>
    /// Name: PartitionColumn. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionColumn => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.PartitionColumn);
    ///<summary>
    /// Name: PartitionScheme. Relationship: Peer
    ///</summary>
    public IEnumerable<TSqlObject> PartitionScheme => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.PartitionScheme);
    ///<summary>
    /// Name: XmlCompressionOptions. Relationship: Composing
    ///</summary>
    public IEnumerable<TSqlObject> XmlCompressionOptions => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlIndex.XmlCompressionOptions);
}

public static class XmlIndexExtensions
{
    public static XmlIndexWrapper ToXmlIndex(this TSqlObject wrapper) => new XmlIndexWrapper(wrapper);
}