// <auto-generated/>
#nullable enable
using Microsoft.SqlServer.Dac.Model;

namespace DacPac.Wrappers;
/// <summary>Provides typed access to a DacFx XmlSchemaCollection object.</summary>
public readonly struct XmlSchemaCollectionWrapper
{
    public readonly Microsoft.SqlServer.Dac.Model.TSqlObject SqlObject;
    /// <summary>Wraps the supplied DacFx object.</summary>
    public XmlSchemaCollectionWrapper(Microsoft.SqlServer.Dac.Model.TSqlObject @object) => SqlObject = @object;
    public string FullName => SqlObject.Name.ToString();
    /// <summary>Gets the Expression property.</summary>
    public string? Expression => (string? )SqlObject.GetProperty(Microsoft.SqlServer.Dac.Model.XmlSchemaCollection.Expression);
    ///<summary>
    /// Name: Schema. Relationship: Hierarchical
    ///</summary>
    public IEnumerable<TSqlObject> Schema => SqlObject.GetReferenced(Microsoft.SqlServer.Dac.Model.XmlSchemaCollection.Schema);
}

public static class XmlSchemaCollectionExtensions
{
    public static XmlSchemaCollectionWrapper ToXmlSchemaCollection(this TSqlObject wrapper) => new XmlSchemaCollectionWrapper(wrapper);
}